// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwntjewqytktcceqpalr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3bnRqZXdxeXRrdGNjZXFwYWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDYzNzQsImV4cCI6MjA2MzU4MjM3NH0.EVe-c2xjEH3OSWMYPNbA-ih7HX_Wzq2eB-2uFJ66-ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);